# -*- coding: utf-8 -*-
"""google gTTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Olr_3rusnlv84dNXouh5HCBd8iQfuvW
"""

! pip install gTTS

from gtts import gTTS
from IPython.display import Audio
from IPython.core.display import display

from google.colab import drive
drive.mount('/content/Drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/Drive/MyDrive/SeSac/datasets

text = "포트홀 녹화를 시작할까요?"
tts = gTTS(text, lang = "ko")
tts.save("intro.mp3")

# 현재 작업중인 디렉토리에 저장된 intro.mp3 파일을 재생해보겠습니다.
wn = Audio("intro.mp3", autoplay = True)
display(wn)

